### ISSUE TITLE
Does this work with pets

### ISSUE THREAD

**Issue by franz101** [OpenTalker/SadTalker#104]
Does it work with animals for example a cat or a dog?

**Comment by Jetpackjules** [comment]
+1

**Comment by vinthony** [comment]
unfortunately, our method only works on real human images, the pets' faces can not be detected.

**Comment by huangxin168** [comment]
I like this interesting idea!
I think you need to change some code:
1. an animal(like dog or cat) face detector/landmark detector.
2. animal face landmark->human face landmark mirroring.
thus makes sadtalker dont know it's animating an animal.

**Comment by franz101** [comment]
woof
