### ISSUE TITLE
请问你们提供api支持么

### ISSUE THREAD

**Issue by dotcool** [OpenTalker/SadTalker#193]
类似这样的，https://replicate.com/devxpy/cog-wav2lip/api ，通过传递参数到sd返回结果，方便对接其他的系统哦

**Comment by dotcool** [comment]
我大致弄了 一个api.py提供了api，服务 ，我帖一下 
[api.zip](https://github.com/Winfredy/SadTalker/files/11270529/api.zip)

**Comment by dotcool** [comment]
我大概写了一个，是配合本地的 dycast的开源项目的。实现一个数字人。但是目前sadtalker生成视频比较慢没法使用哦
[api.zip](https://github.com/Winfredy/SadTalker/files/11330166/api.zip)

**Comment by vinthony** [comment]
这里有一个实现：https://replicate.com/cjwbw/sadtalker
