### ISSUE TITLE
请问新版不支持全身吗？

### ISSUE THREAD

**Issue by muximuxi** [OpenTalker/SadTalker#275]
使用最新版的代码，使用still出来的视频还是256*256的，请问怎样设置才可以是全身的结果？

**Comment by vinthony** [comment]
—preprocess full, 可以查看docs 里的 best practice

**Comment by muximuxi** [comment]
会提示：FileNotFoundError: [Errno 2] No such file or directory: '646bf4b1-c201-4779-a3a6-1d3f336dae2a.mp4'
具体为：然后就是生成视频没有声音
./out_inference/test4_inference_1/2023_05_05_17.37.08/temp_test4##001995_enhanced.mp4: No such file or directory
Traceback (most recent call last):
  File "/home/anaconda3/envs/sd-webui/lib/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '646bf4b1-c201-4779-a3a6-1d3f336dae2a.mp4' -> './out_inference/test4_inference_1/2023_05_05_17.37.08/test4##001995_enhanced.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sd-webui-new/stable-diffusion-webui-master/extensions/SadTalker/inference.py", line 158, in <module>
    main(args)
  File "/home/sd-webui-new/stable-diffusion-webui-master/extensions/SadTalker/inference.py", line 112, in main
    animate_from_coeff.generate(data, save_dir, pic_path, crop_info, \
  File "/home/sd-webui-new/stable-diffusion-webui-master/extensions/SadTalker/src/facerender/animate.py", line 210, in generate
    save_video_with_watermark(enhanced_path, new_audio_path, av_path_enhancer, watermark= False)
  File "/home/sd-webui-new/stable-diffusion-webui-master/extensions/SadTalker/src/utils/videoio.py", line 26, in save_video_with_watermark
    shutil.move(temp_file, save_path)
  File "/home/anaconda3/envs/sd-webui/lib/python3.10/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/home/anaconda3/envs/sd-webui/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/anaconda3/envs/sd-webui/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '646bf4b1-c201-4779-a3a6-1d3f336dae2a.mp4'

**Comment by vinthony** [comment]
再往上的error呢，是不是没有安装ffmpeg

**Comment by muximuxi** [comment]
ffmpeg安装了的：
ffmpeg version 2.8.17-0ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './out_inference/test4_inference_1/2023_05_05_17.37.08/temp_test4##001995.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:04.56, start: 0.000000, bitrate: 86 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 256x256, 82 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Guessed Channel Layout for  Input Stream #1.0 : mono
Input #1, wav, from './out_inference/test4_inference_1/2023_05_05_17.37.08/001995.wav':
  Duration: 00:00:04.56, bitrate: 512 kb/s
    Stream #1:0: Audio: pcm_s32le ([1][0][0][0] / 0x0001), 16000 Hz, 1 channels, s32, 512 kb/s
[aac @ 0x10ada60] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
The generated video is named test4##001995.mp4 in ./out_inference/test4_inference_1/2023_05_05_17.37.08
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
seamlessClone:: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 114/114 [00:30<00:00,  3.74it/s]
ffmpeg version 2.8.17-0ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '6d038814-128d-4d95-b984-fcee335f5558.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf59.27.100
  Duration: 00:00:04.56, start: 0.000000, bitrate: 2567 kb/s
    Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 886x1362 [SAR 1:1 DAR 443:681], 2565 kb/s, 25 fps, 25 tbr, 12800 tbn, 25 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Guessed Channel Layout for  Input Stream #1.0 : mono
Input #1, wav, from './out_inference/test4_inference_1/2023_05_05_17.37.08/001995.wav':
  Duration: 00:00:04.56, bitrate: 512 kb/s
    Stream #1:0: Audio: pcm_s32le ([1][0][0][0] / 0x0001), 16000 Hz, 1 channels, s32, 512 kb/s
[aac @ 0x2440560] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
The generated video is named ./out_inference/test4_inference_1/2023_05_05_17.37.08/test4##001995_full.mp4
face enhancer....
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55b6a2db7080] moov atom not found
Face Enhancer:: 0it [00:00, ?it/s]
ffmpeg version 2.8.17-0ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
./out_inference/test4_inference_1/2023_05_05_17.37.08/temp_test4##001995_enhanced.mp4: No such file or directory

**Comment by muximuxi** [comment]
重新安装了ffmpeg, 可以了~谢谢~~
