### ISSUE TITLE
No Watermark

### ISSUE THREAD

**Issue by LeoLovechest** [OpenTalker/SadTalker#278]
I see there is supposed to be a watermark, I am running on my local pc (not stable diffusion), I am using gfpgan and realesrgan

`python inference.py --driven_audio examples/driven_audio/bet.wav --source_image examples/source_image/harry.png --ref_pose examples/ref_video/better.mp4 --ref_eyeblink examples/ref_video/better.mp4 --result_dir results --preprocess full --still --enhancer gfpgan --background_enhancer realesrgan`

But no watermark is showing and the file for the watermark is in the correct folder, I am glad no watermark is showing but I wonder if I am supposed to be getting better results by unlocking something for it to show or if it has been turned off. My final output file ends in "enhanced" and looks good so I am a bit confused.

**Comment by vinthony** [comment]
sure, we remove the watermark since there previous anyone do not like it :(.
