### ISSUE TITLE
I get a issue when I press generate on webui. 

### ISSUE THREAD

**Issue by eu09** [OpenTalker/SadTalker#301]
Looking for your assist , Im sure the dependencies of package are well installed , however when I click generate button on frontend , then it poll up following error message 

webui-docker-auto-1  | /stable-diffusion-webui/extensions/SadTalker/checkpoints/auido2pose_00140-model.pth
webui-docker-auto-1  | /stable-diffusion-webui/extensions/SadTalker/checkpoints/shape_predictor_68_face_landmarks.dat
webui-docker-auto-1  | /stable-diffusion-webui/extensions/SadTalker/checkpoints/facevid2vid_00189-model.pth.tar
webui-docker-auto-1  | /tmp/25027eceb567812b16051e619f0a4a05ed37380c/tmp10r34kct.png
landmark Det::   0%|          | 0/1 [00:00<?, ?it/s]
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 399, in run_predict
webui-docker-auto-1  |     output = await app.get_blocks().process_api(
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1299, in process_api
webui-docker-auto-1  |     result = await self.call_function(
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1022, in call_function
webui-docker-auto-1  |     prediction = await anyio.to_thread.run_sync(
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
webui-docker-auto-1  |     return await get_asynclib().run_sync_in_worker_thread(
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
webui-docker-auto-1  |     return await future
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
webui-docker-auto-1  |     result = context.run(func, *args)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/call_queue.py", line 15, in f
webui-docker-auto-1  |     res = func(*args, **kwargs)
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/SadTalker/src/gradio_demo.py", line 111, in test
webui-docker-auto-1  |     first_coeff_path, crop_pic_path, crop_info = self.preprocess_model.generate(pic_path, first_frame_dir, preprocess)
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/SadTalker/src/utils/preprocess.py", line 122, in generate
webui-docker-auto-1  |     lm = self.kp_extractor.extract_keypoint(frames_pil, landmarks_path)
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/SadTalker/src/face3d/extract_kp_videos_safe.py", line 39, in extract_keypoint
webui-docker-auto-1  |     current_kp = self.extract_keypoint(image)
webui-docker-auto-1  |   File "/stable-diffusion-webui/extensions/SadTalker/src/face3d/extract_kp_videos_safe.py", line 65, in extract_keypoint
webui-docker-auto-1  |     keypoints = landmark_98_to_68(self.detector.get_landmarks(img)) # [0]
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/facexlib/alignment/awing_arch.py", line 373, in get_landmarks
webui-docker-auto-1  |     pred = calculate_points(heatmaps).reshape(-1, 2)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/facexlib/alignment/awing_arch.py", line 18, in calculate_points
webui-docker-auto-1  |     preds = preds.astype(np.float, copy=False)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
webui-docker-auto-1  |     raise AttributeError(__former_attrs__[attr])
webui-docker-auto-1  | AttributeError: module 'numpy' has no attribute 'float'.
webui-docker-auto-1  | `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
webui-docker-auto-1  | The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
webui-docker-auto-1  |     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by vinthony** [comment]
it seems the numpy are in a higher version: https://stackoverflow.com/questions/74844262/how-can-i-solve-error-module-numpy-has-no-attribute-float-in-python

**Comment by vinthony** [comment]
duplicated in #306 , close this one and discuss in that issue.
