### ISSUE TITLE
WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time!

### ISSUE THREAD

**Issue by newbinxxx** [OpenTalker/SadTalker#349]
新版本升级后，提示  WARNING: The new version of the model will be updated by safetensor, you may need to download it mannully. We run the old version of the checkpoint this time! 请问需要去哪里下载新的模型?

**Comment by aries411** [comment]
同样的问题，你解决了吗？

**Comment by superdreams** [comment]
[SadTalker v0.0.2 rc Release Note](https://github.com/OpenTalker/SadTalker/releases/tag/v0.0.2-rc) 下，webUI运行也出现类似的报错，求解决方式

**Comment by superdreams** [comment]
fixde https://github.com/OpenTalker/SadTalker/commit/743b1d3abff4194b17c2c6fb62589b6b2dc378ce#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959R25
