### ISSUE TITLE
Help you have broken the app!!!

### ISSUE THREAD

**Issue by AIMusicExperiment** [OpenTalker/SadTalker#351]
You have ruined my day!!! I need to use SadTalker on Stable Diffusion right now! You have not put the new models on google drive and don't have a zip file download for us not linex people. As of the new extension commit it is not working at all!!!! Please either offer a way to fix it or but the old commit back up.

**Comment by flyingshan** [comment]
You can find the old releases here: https://github.com/OpenTalker/SadTalker/releases

**Comment by vinthony** [comment]
you can always check out the old version: https://github.com/OpenTalker/SadTalker/commit/c11aa145cf9cf9d745c1cb90064734def798a545

**Comment by AIMusicExperiment** [comment]
Well that is good progress, thanks, but we still have a problem. It will now generate videos, but it throws errors if I try to use GFPGAN: it asks for an argument  and then says it didn't get one. 
![error](https://github.com/OpenTalker/SadTalker/assets/133187055/dc69e7ac-a862-4fc3-8aba-e42564f4f17f)

**Comment by vinthony** [comment]
fixed as in https://github.com/OpenTalker/SadTalker/commit/a810cbe1f21df10dfa286feb037d82b77f82072d

**Comment by AIMusicExperiment** [comment]
I finally have everything working! Thanks for your help, I'm sure it has been a very busy time!  I look forward to the new features and improved performance that this update will undoubtedly offer!

**Comment by Inferencer** [comment]
> 
this had me laughing for a good couple of minutes 

> You have ruined my day!!!
XD XD XD XD

**Comment by vinthony** [comment]
Cool , thanks for the testing and patience.
