### ISSUE TITLE
ValueError: Image data must be a sequence of ndimages.

### ISSUE THREAD

**Issue by userkenny** [OpenTalker/SadTalker#353]
using safetensor as default
{'checkpoint': 'D:\\stable-diffusion-v1.5_webui_new\\extensions\\SadTalker\\checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'D:\\stable-diffusion-v1.5_webui_new/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'D:\\stable-diffusion-v1.5_webui_new/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'D:\\stable-diffusion-v1.5_webui_new/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'D:\\stable-diffusion-v1.5_webui_new\\extensions\\SadTalker\\checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'D:\\stable-diffusion-v1.5_webui_new/extensions/SadTalker/src/config\\facerender.yaml'}
C:\Users\santa\AppData\Local\Temp\tmpenrp44bc.png
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10.91it/s]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 65.83it/s]
mel:: 100%|███████████████████████████████████████████████████████████████████████| 293/293 [00:00<00:00, 82951.81it/s]
audio2exp:: 100%|█████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 225.39it/s]
Face Renderer:: 100%|████████████████████████████████████████████████████████████████| 293/293 [00:37<00:00,  7.81it/s]
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (256, 236) to (256, 240) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
The generated video is named ./results/2ee825cc-8b9b-4652-acfa-778c98c76731/tmpenrp44bc##source9ny59ul7.mp4
Traceback (most recent call last):
  File "D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-v1.5_webui_new/extensions/SadTalker\src\gradio_demo.py", line 85, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess, img_size=size)
  File "D:\stable-diffusion-v1.5_webui_new/extensions/SadTalker\src\facerender\animate.py", line 238, in generate
    imageio.mimsave(enhanced_path, enhanced_images_gen_with_len, fps=float(25))
  File "D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\imageio\v2.py", line 357, in mimwrite
    raise ValueError("Image data must be a sequence of ndimages.")
ValueError: Image data must be a sequence of ndimages.

**while I use win11 ( with GPU 4070Ti implemented) to run SD with sadTalker by "GFPGAN as face enhancer" been checked or selected, I always got running error info as above. However, everything is running fine as long as I unchecked GFPGAN as face enhancer. 

pls give advises, thank you.

**Comment by vinthony** [comment]
it seems something is wrong with PR#303, you can try to replace  `enhanced_images_gen_with_len` with `enhancer`. I will try to find a way to solve this problem today

**Comment by userkenny** [comment]
thanks to prompt reply and I changed 2 places with the said variables in
animate.py. But no luck for me.

Shadow Cun ***@***.***> 於 2023年6月6日 週二 下午5:19寫道：

**Comment by vinthony** [comment]
any logs?

**Comment by zjmnet7213** [comment]
I also have this problem：

using safetensor as default
{'checkpoint': 'D:\\ai\\extensions\\SadTalker\\checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'D:\\ai/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'D:\\ai/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'D:\\ai/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'D:\\ai\\extensions\\SadTalker\\checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'D:\\ai/extensions/SadTalker/src/config\\facerender.yaml'}
C:\Users\Admin\AppData\Local\Temp\gradio\tmp32fs9clo.png

The generated video is named ./results/cc6ec518-370d-40aa-b815-01e81dab85e4/tmp32fs9clo##4月14日-0-100.mp4
Traceback (most recent call last):
  File "D:\ai\py310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\ai\py310\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\ai\py310\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ai\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ai\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\ai\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\ai/extensions/SadTalker\src\gradio_demo.py", line 85, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,  pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None, preprocess=preprocess, img_size=size)
  File "D:\ai/extensions/SadTalker\src\facerender\animate.py", line 238, in generate
    imageio.mimsave(enhanced_path, enhanced_images_gen_with_len, fps=float(25))
  File "D:\ai\py310\lib\site-packages\imageio\v2.py", line 357, in mimwrite
    raise ValueError("Image data must be a sequence of ndimages.")
ValueError: Image data must be a sequence of ndimages.

**Comment by userkenny** [comment]
it looks similar error logs as below,

using safetensor as default
{'checkpoint':
'D:\\stable-diffusion-v1.5_webui_new\\extensions\\SadTalker\\checkpoints\\SadTalker_V0.0.2_256.safetensors',
'dir_of_BFM_fitting':
'D:\\stable-diffusion-v1.5_webui_new/extensions/SadTalker/src/config',
'audio2pose_yaml_path':
'D:\\stable-diffusion-v1.5_webui_new/extensions/SadTalker/src/config\\auido2pose.yaml',
'audio2exp_yaml_path':
'D:\\stable-diffusion-v1.5_webui_new/extensions/SadTalker/src/config\\auido2exp.yaml',
'use_safetensor': True, 'mappingnet_checkpoint':
'D:\\stable-diffusion-v1.5_webui_new\\extensions\\SadTalker\\checkpoints\\mapping_00229-model.pth.tar',
'facerender_yaml':
'D:\\stable-diffusion-v1.5_webui_new/extensions/SadTalker/src/config\\facerender.yaml'}
C:\Users\santa\AppData\Local\Temp\tmpzw9ec3h4.png
landmark Det::
100%|███████████████████████████████████████████████████████████████████████████████████|
1/1 [00:00<00:00, 11.45it/s]
3DMM Extraction In Video::
100%|███████████████████████████████████████████████████████████████████████|
1/1 [00:00<00:00, 39.99it/s]
mel::
100%|█████████████████████████████████████████████████████████████████████████████████████|
293/293 [00:00<00:00, 71387.22it/s]
audio2exp::
100%|███████████████████████████████████████████████████████████████████████████████████|
30/30 [00:00<00:00, 233.81it/s]
Face Renderer::
100%|██████████████████████████████████████████████████████████████████████████████|
293/293 [00:37<00:00,  7.85it/s]
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by
macro_block_size=16, resizing from (256, 232) to (256, 240) to ensure video
compatibility with most codecs and players. To prevent resizing, make your
input image divisible by the macro_block_size or set the macro_block_size
to 1 (risking incompatibility).
The generated video is named
./results/eedcbf29-6bf9-42be-b797-215aa2c6c5b1/tmpzw9ec3h4##sourcecj6te_ho.mp4
Traceback (most recent call last):
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\gradio\routes.py",
line 337, in run_predict
    output = await app.get_blocks().process_api(
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\gradio\blocks.py",
line 1015, in process_api
    result = await self.call_function(
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\gradio\blocks.py",
line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\anyio\to_thread.py",
line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\anyio\_backends\_asyncio.py",
line 937, in run_sync_in_worker_thread
    return await future
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\anyio\_backends\_asyncio.py",
line 867, in run
    result = context.run(func, *args)
  File
"D:\stable-diffusion-v1.5_webui_new/extensions/SadTalker\src\gradio_demo.py",
line 85, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,
 pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None,
preprocess=preprocess, img_size=size)
  File
"D:\stable-diffusion-v1.5_webui_new/extensions/SadTalker\src\facerender\animate.py",
line 240, in generate
    imageio.mimsave(enhanced_path, enhancer, fps=float(25))
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\imageio\v2.py",
line 357, in mimwrite
    raise ValueError("Image data must be a sequence of ndimages.")
ValueError: Image data must be a sequence of ndimages.

Shadow Cun ***@***.***> 於 2023年6月6日 週二 下午6:06寫道：

**Comment by vinthony** [comment]
It because of the error in imageio version of SDWEBUI,

fixed in https://github.com/OpenTalker/SadTalker/commit/a810cbe1f21df10dfa286feb037d82b77f82072d

**Comment by userkenny** [comment]
Hello, I made these changes to your advise both in SD-weibu launch.py and
animate,py as well.  After fresh restart of SD-weibu, it looks the similar
error log to below.
Still, without "GFPGAN as face enhance" selected, the sadTalker extension
would run well. I am using win11 SD-weibu with Nvidia 4070ti.

using safetensor as default
{'checkpoint':
'D:\\stable-diffusion-v1.5_webui_new\\extensions\\SadTalker\\checkpoints\\SadTalker_V0.0.2_256.safetensors',
'dir_of_BFM_fitting':
'D:\\stable-diffusion-v1.5_webui_new/extensions/SadTalker/src/config',
'audio2pose_yaml_path':
'D:\\stable-diffusion-v1.5_webui_new/extensions/SadTalker/src/config\\auido2pose.yaml',
'audio2exp_yaml_path':
'D:\\stable-diffusion-v1.5_webui_new/extensions/SadTalker/src/config\\auido2exp.yaml',
'use_safetensor': True, 'mappingnet_checkpoint':
'D:\\stable-diffusion-v1.5_webui_new\\extensions\\SadTalker\\checkpoints\\mapping_00229-model.pth.tar',
'facerender_yaml':
'D:\\stable-diffusion-v1.5_webui_new/extensions/SadTalker/src/config\\facerender.yaml'}
C:\Users\santa\AppData\Local\Temp\tmpid1ybxjp.png
landmark Det::
100%|█████████████████████████████████████████████████████████████████████|
1/1 [00:00<00:00, 10.50it/s]
3DMM Extraction In Video::
100%|█████████████████████████████████████████████████████████| 1/1
[00:00<00:00, 44.07it/s]
mel::
100%|███████████████████████████████████████████████████████████████████████|
293/293 [00:00<00:00, 72627.57it/s]
audio2exp::
100%|█████████████████████████████████████████████████████████████████████|
30/30 [00:00<00:00, 213.41it/s]
Face Renderer::
100%|████████████████████████████████████████████████████████████████|
293/293 [00:38<00:00,  7.57it/s]
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by
macro_block_size=16, resizing from (256, 266) to (256, 272) to ensure video
compatibility with most codecs and players. To prevent resizing, make your
input image divisible by the macro_block_size or set the macro_block_size
to 1 (risking incompatibility).
The generated video is named
./results/cdb4a2ba-8975-42c0-a3ab-66a8b2096258/tmpid1ybxjp##sourcexg07nd73.mp4
Traceback (most recent call last):
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\gradio\routes.py",
line 337, in run_predict
    output = await app.get_blocks().process_api(
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\gradio\blocks.py",
line 1015, in process_api
    result = await self.call_function(
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\gradio\blocks.py",
line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\anyio\to_thread.py",
line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\anyio\_backends\_asyncio.py",
line 937, in run_sync_in_worker_thread
    return await future
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\anyio\_backends\_asyncio.py",
line 867, in run
    result = context.run(func, *args)
  File
"D:\stable-diffusion-v1.5_webui_new/extensions/SadTalker\src\gradio_demo.py",
line 85, in test
    return_path = self.animate_from_coeff.generate(data, save_dir,
 pic_path, crop_info, enhancer='gfpgan' if use_enhancer else None,
preprocess=preprocess, img_size=size)
  File
"D:\stable-diffusion-v1.5_webui_new/extensions/SadTalker\src\facerender\animate.py",
line 241, in generate
    imageio.mimsave(enhanced_path, enhancer, fps=float(25))
  File
"D:\stable-diffusion-v1.5_webui_new\venv\lib\site-packages\imageio\v2.py",
line 357, in mimwrite
    raise ValueError("Image data must be a sequence of ndimages.")
ValueError: Image data must be a sequence of ndimages.

Shadow Cun ***@***.***> 於 2023年6月7日 週三 上午12:10寫道：

**Comment by zjmnet7213** [comment]
> 我也有这个问题：
> 
> 使用safetensor作为默认值{'checkpoint'： 'D：\ai\extensions\SadTalker\checkpoints\SadTalker_V0.0.2_256.safetensors'， 'dir_of_BFM_fitting'： 'D：\ai/extensions/SadTalker/src/config'， 'audio2pose_yaml_path'： 'D：\ai/extensions/SadTalker/src/config\auido2pose.yaml'， 'audio2exp_yaml_path'： 'D：\ai/extensions/SadTalker/src/config\auido2exp.yaml'， 'use_safetensor'： True， 'mappingnet_checkpoint'： 'D：\ai\extensions\SadTalker\checkpoints\mapping_00229-model.pth.tar'， 'facerender_yaml'： 'D：\ai/extensions/SadTalker/src/config\facerender.yaml'} C：\Users\Admin\AppData\Local\Temp\gradio\tmp32fs9clo.png
> 
> 生成的视频名为 ./results/cc6ec518-370d-40aa-b815-01e81dab85e4/tmp32fs9clo##4月14日-0-100.mp4 回溯（最近一次调用）：文件 “D：\ai\py310\lib\site-packages\gradio\routes.py”，第 422 行，在 run_predict 输出 = 等待 app.get_blocks（）.process_api（ 文件 “D：\ai\py310\lib\site-packages\gradio\blocks.py”，第 1323 行，在 process_api result = await self.call_function（ 文件 “D：\ai\py310\lib\site-packages\gradio\blocks.py”，第 1051 行，在 call_function 预测 = 等待 anyio.to_thread.run_sync（ 文件 “D：\ai\py310\lib\site-packages\anyio\to_thread.py”，第 31 行，run_sync返回等待 get_asynclib（）.run_sync_in_worker_thread（ 文件 “D：\ai\py310\lib\site-packages\anyio_backends_asyncio.py”，第 937 行，在 run_sync_in_worker_thread 返回等待未来 文件 “D：\ai\py310\lib\site-packages\anyio_backends_asyncio.py”，第 867 行，在运行结果 = context.run（func， *args） 文件 “D：\ai/extensions/SadTalker\src\gradio_demo.py”，第 85 行，在测试 return_path = self.animate_from_coeff.generate（data， save_dir， pic_path， crop_info， enhancer='gfpgan' 如果 use_enhancer 否则 None， preprocess=preprocess， img_size=size） 文件 “D：\ai/extensions/SadTalker\src\facerender\animate.py”， 第 238 行，在 generate imageio.mimsave（enhanced_path， enhanced_images_gen_with_len， fps=float（25）） 文件 “D：\ai\py310\lib\site-packages\imageio\v2.py”中，第 357 行，在 mimwrite raise ValueError（“Image data 必须是 ndimages 序列。值错误：图像数据必须是一系列新图像。

**Comment by zjmnet7213** [comment]
The updated new version solves this problem

**Comment by userkenny** [comment]
new sadTalker vresion?

zjmnet7213 ***@***.***> 於 2023年6月7日 週三 下午12:10寫道：

**Comment by userkenny** [comment]
yes, as of today's SD-weibu version with today's  sadTalker would resolve
the above issue. thanks to advise.

zjmnet7213 ***@***.***> 於 2023年6月7日 週三 下午12:53寫道：

**Comment by vinthony** [comment]
cool! i will close it since it has been solved.

**Comment by userkenny** [comment]
yes & thank you

Shadow Cun ***@***.***> 於 2023年6月13日 週二 下午4:47寫道：

**Comment by why-is-me** [comment]
I have used the latest version of SD webui (1.6) and the current latest SadTalker (0.0.2), but I still reported the following similar error：

**Comment by S3X33** [comment]
How to get a new version of update sadtalker?Should I delete all documents been downloaded and try it again?
