### ISSUE TITLE
Issue KeyError: 'checkpoint'

### ISSUE THREAD

**Issue by wishky2k2** [OpenTalker/SadTalker#358]
I have this error when run Sadtalker
![image](https://github.com/OpenTalker/SadTalker/assets/116348606/66e4fc73-d4cb-4632-9a51-70f3a63eee2a)

**Comment by wishky2k2** [comment]
> it should be fixed in a new commit

it work thanks u

**Comment by ZHAOKUNPENG111** [comment]
How did you solve this problem

**Comment by ZHAOKUNPENG111** [comment]
> it should be fixed in a new commit

How did you solve this problem

**Comment by ZHAOKUNPENG111** [comment]
> > it should be fixed in a new commit
> 
> it work thanks u

How did you solve this problem
