### ISSUE TITLE
How to use the new 512 size  beta  face model?

### ISSUE THREAD

**Issue by hwang824** [OpenTalker/SadTalker#359]
How to use the new 512 face model to generate 512 size video? Can you give some examples about commands or parameters?

**Comment by hwang824** [comment]
Should I call inference.py by --size 512 to use the new 512 size beta face model?

**Comment by vinthony** [comment]
sure, make sure you have downloaded the lastest version checkpoints in `safetensor`

**Comment by hwang824** [comment]
Thanks for your warmly help!

**Comment by vinthony** [comment]
Closed it because it has been solved.
