### ISSUE TITLE
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

### ISSUE THREAD

**Issue by mengmeng889** [OpenTalker/SadTalker#363]
Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1848, in preprocess
    return self._format_image(im)
  File "F:\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1796, in _format_image
    path = self.pil_to_temp_file(
TypeError: save_pil_to_file() got an unexpected keyword argument 'format'

What can I do to solve this problem, please?

**Comment by Tobe2d** [comment]
I am facing the save problem, could you share how you solved it?

**Comment by aniellod** [comment]
Same here. 
uname -a Linux mint 5.19.0-43-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Some package versions 
`Package                  Version
------------------------ ---------------
bitsandbytes             0.37.2
blendmodes               2022
clip                     1.0
diffusers                0.14.0
discord-webhook          0.17.0
ffmpy                    0.3.0
gfpgan                   1.3.8
gradio                   3.23.0
huggingface-hub          0.13.4
numpy                    1.24.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
open-clip-torch          2.7.0
opencv-python            4.7.0.72
pytorch-lightning        1.9.4
realesrgan               0.3.0
safetensors              0.3.0
svglib                   1.5.1
sympy                    1.11.1
torch                    2.0.0
torchdiffeq              0.2.3
torchmetrics             0.11.4
torchsde                 0.2.5
torchvision              0.15.1
transformers             4.25.1
websocket-client         1.5.1
websockets               11.0
wheel                    0.40.0
yapf                     0.32.0`

**Comment by vinthony** [comment]
is this discussion helpful?: https://github.com/OpenTalker/SadTalker/issues/378#issuecomment-1585527113

**Comment by Yrbashazar** [comment]
i have a same probleme with A1111, help us please !

**Comment by cauckfgf** [comment]
`def pil_to_temp_file(self, img: _Image.Image, dir: str, format="png") -> str:
        bytes_data = processing_utils.encode_pil_to_bytes(img, format)
        temp_dir = Path(dir) / self.hash_bytes(bytes_data)
        temp_dir.mkdir(exist_ok=True, parents=True)
        filename = str(temp_dir / f"image.{format}")
        img.save(filename, pnginfo=processing_utils.get_pil_metadata(img))
        return filename`
the function has ”format“，why this error？
