### ISSUE TITLE
为什么单张图，actor的头部会动？

### ISSUE THREAD

**Issue by Wentao795** [OpenTalker/SadTalker#376]
您好，非常感谢您的工作。我在测试时候发现，输入即使是单张图，输出的视频头部也会动？你能告诉我这是为什么吗？有什么方法可以控制头部运动吗？期待您的回复~~

**Comment by vinthony** [comment]
目前是根据音频生成的头部动作，可以看best practice文档中的ref_pose参数，可以迁移另一个视频的头动。

**Comment by Wentao795** [comment]
> 目前是根据音频生成的头部动作，具体可以看我们的paper。控制头动的话可以看best practice文档中的ref_pose参数，可以迁移另一个视频的头动。

好的，感谢您的回复。还有个问题，在full模式下，生成的图像贴回原图，怎么可以保持头不动？
