### ISSUE TITLE
怎么给webui改个ip和端口，不用127.0.0.1，也不用7860端口

### ISSUE THREAD

**Issue by luochaolun** [OpenTalker/SadTalker#394]
同时装了sd和sadtalker，用的都是7860端口，不能同时运行！
还有在腾讯云上，怎么用公网ip:port形式访问？
比如IP是123.123.123.123,端口是4567，
怎么改可以用http://123.123.123.123:4567/来访问？

还有就是用webui.sh来访问，得把checkpoints改成checkpoint才行

**Comment by newbinxxx** [comment]
修改 launcher.py 
 demo.launch(server_port=6666)

**Comment by newbinxxx** [comment]
ip是改  server_name="0.0.0.0"

**Comment by luochaolun** [comment]
确实可以，非常感谢！
