### ISSUE TITLE
Can you rename the app.py to get rid of errors(for Automatic1111 WebUI)? and a Temporary Fix

### ISSUE THREAD

**Issue by FlowDownTheRiver** [OpenTalker/SadTalker#408]
Error executing callback ui_tabs_callback for C:\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\script_callbacks.py", line 151, in ui_tabs_callback
    res += c.callback() or []
  File "C:\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 172, in on_ui_tabs
    from app import sadtalker_demo
ImportError: cannot import name 'sadtalker_demo' from 'app' (C:\stable-diffusion-webui\venv\lib\site-packages\app\__init__.py)

[fix_sad_talker.zip](https://github.com/OpenTalker/SadTalker/files/11752469/fix_sad_talker.zip)
place the zip file in sadtalker directory.(stable-diffusion-webui\extensions\SadTalker),launch the bat file.

Tried this on windows.
I have renamed it to appy.py and changed the import statements coming from it and it fixed the issue.But every commit it breaks again. Seems like app.py is not a good choice for a filename at least for automatic's WebUI. You can rename it to anything.

it has been reported in here :  https://github.com/OpenTalker/SadTalker/issues/390

**Comment by JunSong1** [comment]
![image](https://github.com/OpenTalker/SadTalker/assets/40349823/b8fa9adc-1602-485a-b7ab-17b66a177d9b)
我使用的是秋叶的sd-webui启动器，在启动的时候也遇到了这样的问题，按照您提供的解决方式，也没有解决问题，不知道是不是我那里弄错了！

**Comment by FlowDownTheRiver** [comment]
> ![image](https://user-images.githubusercontent.com/40349823/245972287-b8fa9adc-1602-485a-b7ab-17b66a177d9b.png) 我使用的是秋叶的sd-webui启动器，在启动的时候也遇到了这样的问题，按照您提供的解决方式，也没有解决问题，不知道是不是我那里弄错了！

I have reuploaded the zip file,I forgot to include the "launcher.py" edit. 

But your problem seems like a missing python library.Not related directly to this issue.

**Comment by JunSong1** [comment]
OK，我现在已经成功的使用webui.bat启动了sadtalker；确实是因为我没有安装相应的python包；但是我并没有遇到您上面所说的问题，gradio版本问题没有在我这里出现过，我就是按照requirements.txt里面的库版本进行安装的！最后也能成功的运行sadTalker!

**Comment by FlowDownTheRiver** [comment]
> OK，我现在已经成功的使用webui.bat启动了sadtalker；确实是因为我没有安装相应的python包；但是我并没有遇到您上面所说的问题，gradio版本问题没有在我这里出现过，我就是按照requirements.txt里面的库版本进行安装的！最后也能成功的运行sadTalker!

I am glad to hear that. ;)

**Comment by vinthony** [comment]
Hi, I have renamed the app.py to another name :) thanks for this temporal fixed.

**Comment by FlowDownTheRiver** [comment]
> Hi, I have renamed the app.py to another name :) thanks for this temporal fixed.

Thank you very much. It is much better when the official repo fixes the problem and thanks for the project.
