### ISSUE TITLE
Notification: scheduled to be listied on stable diffusion webui extension index

### ISSUE THREAD

**Issue by w-e-w** [OpenTalker/SadTalker#477]
@vinthony 
Hi, I'm one of the maintainers of stable diffusion webui extensions index
we received a request to add this project to the stable diffusion webui extensions index
I intend to add this if no objection is raised by 7/13 see PR https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/115

if you wish to not have this listed on the extension index or make any changes to the descriptions or tags, please leave a comment or open a new pull request soon
```json
{
    "name": "SadTalker",
    "url": "https://github.com/OpenTalker/SadTalker.git",
    "description": "Generating talking head videos with facial image and speech audio",
    "tags": [
        "tab",
        "animation"
    ]
}
```

**Comment by vinthony** [comment]
cool, Thanks!

**Comment by w-e-w** [comment]
since you have confirmed I merged it just now
