### ISSUE TITLE
ERROR: No matching distribution found for torch==1.12.1+cu113 / Windows

### ISSUE THREAD

**Issue by MrMarkoz** [OpenTalker/SadTalker#515]
Hello,  I am trying to install SadTalker and when I open webui.bat I got this error:

```
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Commit hash: <none>
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu113 (from versions: 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.12.1+cu113

[notice] A new release of pip is available: 23.1.2 -> 23.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "D:\SadTalker-main\Launcher.py", line 203, in <module>
    prepare_environment()
  File "D:\SadTalker-main\Launcher.py", line 187, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "D:\SadTalker-main\Launcher.py", line 70, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "D:\SadTalker-main\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
Error code: 1
```

I already installed PyTorch 2.0.1 from their webpage and also upgraded pip to 23.2 but it still says that I have the previous version.
 
I have a Windows 11

**Comment by ceun** [comment]
I see you are running into an issue installing PyTorch 1.12.1 with Python 3.11.4. The SadTalker project specifically requires Python 3.10.6 to be compatible with the PyTorch version it uses. 

To resolve this:

1. Uninstall Python 3.11.4 and install Python 3.10.6, making sure to check "Add Python to PATH" during the installation process.

2. Open a new command prompt and activate the SadTalker virtual environment:

cd SadTalker-main
scripts\venv\activate

3. Inside the virtual environment, upgrade pip:

python -m pip install --upgrade pip

4. Install the required PyTorch version:

pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113

By using Python 3.10.6 and creating a separate virtual environment, you will isolate the project dependencies and versions from your global Python installation.

**Comment by MrMarkoz** [comment]
Thank you so much! It worked now

**Comment by Cyurainya** [comment]
I have the same issue in Linux. But I can not fix it with the solution you had show above.

**Comment by madmistermump** [comment]
This is a significant problem for new installs. Python version 3.10.6 is no longer available from python, so if you don't have it you are pretty much out of luck unless someone has an old version to install. The main issue is pytorch is not compatible with anything after 3.10.6. Python is (at the time of my post) 3.13 so unless pytorch updates their software this git is unless for new installs.
