### ISSUE TITLE
关于ExpNet中lipreading loss的问题

### ISSUE THREAD

**Issue by WCZ93762** [OpenTalker/SadTalker#548]
论文中的ExpNet在训练过程中，基于deep3d渲染帧和音频分别作为输入，利用lipreading model分别输出预测的logits然后计算交叉熵loss，可是在复现的时候发现交叉熵loss大到离谱，在实测时发现需要大约1s的视频（即25帧）才有可能对齐音频所预测的logits。

请问lipreading loss的计算确实是仅依赖5帧渲染帧吗？还是使用了抽样策略选取5帧。

**Comment by rzwang111** [comment]
请问两个logits的计算是针对哪一部分输入呢。从wav2lip生成的帧提取参数然后重建5帧作为gt，以模型输出的beta和wav2lip的其他coeffs作为预测吗。

**Comment by WCZ93762** [comment]
你好，已收到，感谢

**Comment by LebornCC** [comment]
请问你解决了吗

**Comment by WCZ93762** [comment]
你好，已收到，感谢

**Comment by cyrala** [comment]
> 论文中的ExpNet在训练过程中，基于deep3d渲染帧和音频分别作为输入，利用lipreading model分别输出预测的logits然后计算交叉熵loss，可是在复现的时候发现交叉熵loss大到离谱，在实测时发现需要大约1s的视频（即25帧）才有可能对齐音频所预测的logits。
> 
> 请问lipreading loss的计算确实是仅依赖5帧渲染帧吗？还是使用了抽样策略选取5帧。

请问你解决了吗？我在复现的时候交叉熵loss也非常大

**Comment by WCZ93762** [comment]
你好，已收到，感谢

**Comment by WCZ93762** [comment]
> 请问两个logits的计算是针对哪一部分输入呢。从wav2lip生成的帧提取参数然后重建5帧作为gt，以模型输出的beta和wav2lip的其他coeffs作为预测吗。

不好意思，之前已经停止复现该论文了，不过我当初的复现确实是按这个方案进行尝试

**Comment by cyrala** [comment]
> > 请问两个logits的计算是针对哪一部分输入呢。从wav2lip生成的帧提取参数然后重建5帧作为gt，以模型输出的beta和wav2lip的其他coeffs作为预测吗。
> 
> 不好意思，之前已经停止复现该论文了，不过我当初的复现确实是按这个方案进行尝试

好的，谢谢，我再试试问问作者

**Comment by WCZ93762** [comment]
> > 论文中的ExpNet在训练过程中，基于deep3d渲染帧和音频分别作为输入，利用lipreading model分别输出预测的logits然后计算交叉熵loss，可是在复现的时候发现交叉熵loss大到离谱，在实测时发现需要大约1s的视频（即25帧）才有可能对齐音频所预测的logits。
> > 请问lipreading loss的计算确实是仅依赖5帧渲染帧吗？还是使用了抽样策略选取5帧。
> 
> 请问你解决了吗？我在复现的时候交叉熵loss也非常大

没有解决，记得强制加了个很小的系数，但是复现的效果也不好，建议不用再复现该工作了，目前已经有更好的工作出现

**Comment by chaolongy** [comment]
> > > 论文中的ExpNet在训练过程中，基于deep3d渲染帧和音频分别作为输入，利用lipreading model分别输出预测的logits然后计算交叉熵loss，可是在复现的时候发现交叉熵loss大到离谱，在实测时发现需要大约1s的视频（即25帧）才有可能对齐音频所预测的logits。
> > > 请问lipreading loss的计算确实是仅依赖5帧渲染帧吗？还是使用了抽样策略选取5帧。
> > 
> > 
> > 请问你解决了吗？我在复现的时候交叉熵loss也非常大
> 
> 没有解决，记得强制加了个很小的系数，但是复现的效果也不好，建议不用再复现该工作了，目前已经有更好的工作出现

目前更好的开源工作是哪个？感谢你的答复！
