### ISSUE TITLE
请问在webui上有类似/sdapi/v1/txt2img这种的api吗？

### ISSUE THREAD

**Issue by liwu96** [OpenTalker/SadTalker#614]
各位大佬，我在stable diffusion webui上运行，想基于webui上的api调用生成，请问有类似/sdapi/v1/txt2img这种的api吗？

**Comment by jxyk2007** [comment]
`python inference.py --driven_audio <audio.wav> \
                    --source_image <video.mp4 or picture.png> \
                    --result_dir <a file to store results> \
                    --still \
                    --preprocess full \
                    --enhancer gfpgan `



根据这个，自己写api 啊

**Comment by a958330481** [comment]
有的，https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API
